[openLISEM runfile version 6.0]

[Input]
Result datetime=0
Include Satellite Image=0
satImage Directory=
satImage File=
mpegexe Directory=

[Output]
Main results file=totals.csv
Total Series file=totalseries.csv
Filename point output=hydrographs.csv
Add timestamp=0
Report discharge units=0
Timeplot as PCRaster=0
Report digits out=3
Minimum reported flood height=1.0
Report format GTiff=0
End run report=1
Rainfall map=rainfall.map
Interception map=interception.map
Infiltration map=infiltration.map
Runoff map=Flowcumm3.map
WH max level map=whmax.map
Channel discharge map=chandism3.map
Channel Max Q=chanmaxq.map
Channel Max WH=chanmaxwh.map
Max Velocity=Vmax.map
Max Momentum=VHmax.map
Flood time map=floodtime.map
Flood start time=floodstart.map
Storm Drain map=Stormdrain.map
Storm Drain Vol map=
Erosion map=detachment.map
Deposition map=deposition.map
Soilloss map=soilloss.map
Channel detachment map=chandet.map
Channel deposition map=chandep.map
Filename landunit output=totlandunit.csv
Flood stats=floodstats.csv

[Simulation times]

[Meteo]
Include Rainfall=0
Event based=0
Rainfall file=rain.txt
Rainfall Directory=C:/Nogames/LISEM/VNIIMZ_10m/
Rainfall ID interpolation=0
IDI factor=1.0
Use Rainfall maps=0
Rainfall maplist name=
Rainfall Map Directory=C:/Nogames/LISEM/VNIIMZ_Bas/rain/
Rainfall Bias Correction=1.0
Include ET=0
Daily ET=1
ET file=
ET Directory=
Use ET maps=0
ET maplist name=
ET Map Directory=
ET Bias Correction=1.0
Rainfall ET threshold=1.0
Include channel inflow=0
Discharge inflow file=
Discharge inflow directory=
Include water height inflow=0
Water level inflow file=
Water level inflow directory=

[Interception]
Include Interception=0
Canopy storage equation=2
Include litter interception=0
Litter interception storage=1.0

[Infiltration]
Include Infiltration=0
Infil Method=3
Include compacted=0
Include crusts=0
Dynamic crusting=0
Impermeable sublayer=0
Use one matrix potential=0
Initial matrix potential=-100
Nr input layers=2
Psi user input=0
Swatre profile file=profile.inp
Swatre table directory=C:/Nogames/LISEM/
SWATRE internal minimum timestep=1
Swatre output=0
Swatre dry=0
Matric head files=inithead
Include tile drains=0
Tile entry suction=-10
SoilWB nodes 1=3
SoilWB nodes 2=3
SoilWB nodes 3=3
Infil Kavg=0
Van Genuchten=1

[Flow]
Routing Kin Wave 2D=0
Flow Boundary 2D=1
Flood initial level map=0
Flooding courant factor=1.0
Timestep flood=0,20
Correct DEM=0
Use 2D Diagonal flow=1
Flood solution=1

[Channel and Groundwater]
Include main channels=0
Include channel infil=0
Include stationary baseflow=0
Include channel culverts=0
Include GW flow=0
GW flow explicit=1
GW flow SWOF=0
GW flow LDD=0
GW flow SWAT=0
GW recharge factor=1.0
GW flow factor=1.0
GW threshold factor=1.0
GW slope factor=1.0
GW deep percolation=1.0

[Infrastructure]
Include Infrastructure=0
Include buildings=0
Include raindrum storage=0
Add buildings to DEM=0
Add building fraction=1.0
Add building height=1.0
Hard Surfaces=0
Include road system=0
Include storm drains=0
Storm drain shape=1
Drain inlet distance=20
Drain inlet size=1.0

[Erosion]
Include Erosion simulation=0
[Splash]
KE parameters EQ1=1;21.00;1.0;1.0
KE parameters EQ2=0;1.00;1.0
KE parameters EQ3=0;1.00;1.0
KE time based=0
Splash Delivery Ratio=1.0
Splash equation=1
No detachment boundary=0
[Sediment]
Detachment efficiency=2
Settling Velocity=1
Flooding SS method=1
Flooding BL method=2
Include diffusion=0
Detachment efficiency channel=2
Direct efficiency channel=1.00
Turbulence factor channel=1.0
River SS method=2
Use 2 phase flow=0
River BL method=2
Include River diffusion=0
Sigma diffusion=1.0

[Conservation]
Include Mitigation/Conservation=0
Include buffers=0
Include flow barriers=0
Flow barrier table filename=flowbarriers.txt
Include grass strips=0
Grassstrip Mannings n=1.0
Include Sediment traps=0
Sediment Trap Mannings n=1.0
Include subgridcell retention=0

[Calibration]
Grain Size calibration D50=1.0
Grain Size calibration D90=1.0
Smax calibration=1.0
RR calibration=1.0
Ksat calibration=1.0
Ksat2 calibration=1.0
Ksat3 calibration=1.0
N calibration=1
Theta calibration=1.0
Psi calibration=1.0
Channel Ksat calibration=1.0
Channel N calibration=1
Boundary water level calibration=1.0
Channel tortuosity=1.0
Cohesion calibration=1.0
Cohesion Channel calibration=1.0
Aggregate stability calibration=1.0

[Output maps]
Erosion map units (0/1/2)=0
Output interval=1
OutRunoff=0
OutWH=0
OutV=0
OutInterception=0
OutSurfStor=0
OutInf=0
OutTileDrain=0
OutTheta=0
OutGW=0
OutTileVol=0
OutDet=0
OutDep=0
OutTC=0
OutConc=0
OutSed=0
OutSL=0
OutSedSS=0
OutSedBL=0

[Advanced]
Nr user Cores=0
Flooding SWOF Reconstruction=3
Flooding SWOF flux limiter=1
Correct MB with WH=0
Flood max iterations=200
Use time avg V=1
Erosion outside 2D loop=1
Pit Value=1.0
Use linked list=0
Use Perimeter KW=0
Use Channel Kinwave dt=0
Channel KinWave dt=60
Use Channel Max V=1
Channel Max V=1.0
Channel 2D flow connect=0
SWATRE precision=6
Advanced Options=0

[map names]

[Rainfall]
ID=mask0.map
IDGauges=mask0.map
ETID=ETID.map

[Catchment]
dem=dem.map
grad=grad.map
ldd=ldd.map
outlet=outlet.map
outpoint=outpoint.map
flowboundary=flowboundary.map

[Landuse]
landunit=landunit.map
cover=per.map
litter=litter.map
lai=lai.map
ch=ch.map
smax=smax.map

[Surface]
rr=rr.map
manning=n.map
stonefrc=stonefrc.map
crustfrc=crustfrc.map
compfrc=compfrc.map

[Infiltration]
[Swatre]
profmap=profile.map
profcrst=profcrst.map
profcomp=profcomp.map
profgras=profgras.map
inithead=inithead
[1st layer Green&Ampt/Smith&Parlange]
ksat1=ksat1.map
psi1=psi1.map
thetas1=thetas1.map
thetai1=thetai1.map
soildep1=soildep1.map
[2nd layer Green&Ampt/Smith&Parlange]
ksat2=ksat2.map
psi2=psi2.map
thetas2=thetas2.map
thetai2=thetai2.map
soildep2=soildep2.map
[3rd layer Green&Ampt/Smith&Parlange]
ksat3=ksat3.map
psi3=psi3.map
thetas3=thetas3.map
thetai3=thetai3.map
soildep3=soildep3.map
[Surafce features influencing infiltration]
OMmap=omcorr.map
Densmap=densfact.map
ksatcrst=ksatcrst.map
porecrst=porecrst.map
ksatcomp=ksatcomp.map
porecomp=porecomp.map

[Channels and Groundwater]
lddchan=lddchan.map
chanwidth=chanwidt.map
chandepth=chandepth.map
changrad=changrad.map
chanside=chanside.map
chandiam=chandiameter.map
chancul=chanculvert.map
chanman=chanman.map
chanksat=chanksat.map
qinpoints=QinPoints.map
chancoh=chancoh.map
baseflow=baseflow.map
lddbase=lddbaseflow.map
basereach=basedistance.map
whinit=WHinit.map
whbound=whboundary.map

[Buildings and roads]
road=roadwidt.map
housecover=housecover.map
roofstore=roofstore.map
drumstore=drumstore.map
hardsurf=hardsurf.map

[Erosion]
coh=coh.map
cohadd=cohadd.map
aggrstab=aggrstab.map
d50=d50_10m.map
d90=d90_10m.map

[Mitigation]
buffers=buffers.map
gridretention=gridretention.map
chanretention=chanretention.map
sedretmax=sedretmax.map
grasswidth=grasswid.map
ksatgras=ksatgras.map
poregras=poregras.map
cohgras=cohgras.map
flowbarrierindex=flowbarrierindex.map

[Storm drains/Tile drains]
lddtile=lddtile.map
tilediameter=tilediameter.map
tilewidth=tilewidth.map
tileheight=tileheight.map
tiledepth=tiledepth.map
tilegrad=tilegrad.map
tileman=tileman.map
Map Directory=/home/jovyan/work/LISEM 3/inputfiles/VNIIMZ_10m/maps_probnik_10m/
Result Directory=/home/jovyan/work/LISEM 3/inputfiles/VNIIMZ_10m/res_10m/
Begin Time=2024-01-01 00:00
End Time=2024-01-01 00:30
Timestep=60
Report interval=5
