[openLISEM runfile version 6.0]

[Input]
Map Directory=/home/jovyan/work/LISEM/inputfiles/VNIIMZ_20m/maps
Result datetime=0

[Output]
Result Directory=/home/jovyan/work/LISEM/results_simple
Main results file=totals.csv
Add timestamp=0
End run report=1

[Simulation times]
Begin time=001:0000
End time=001:0060
Timestep=120.0

[Meteo]
Include Rainfall=1
Rainfall file=rain.txt
Rainfall Directory=/home/jovyan/work/LISEM/inputfiles/VNIIMZ_20m

[Infiltration]
Include Infiltration=0
Infil Method=3  # ДОБАВЛЕНО: обязательный параметр в новой версии

[Flow]
Routing Kin Wave 2D=2
Flow Boundary 2D=1
Use 2D Diagonal flow=1

[Erosion]
Include Erosion simulation=0

[map names]
dem=dem.map
grad=grad.map
ldd=ldd.map
outlet=outlet.map
landunit=landunit.map
cover=per.map
manning=n.map
rr=rr.map