[Input]
Map Directory=/home/jovyan/work/LISEM/inputfiles/VNIIMZ_20m/maps
Result datetime=0

[Output]
Result Directory=/home/jovyan/work/LISEM/results_test
Main results file=totals.csv
Add timestamp=0
End run report=1

[Simulation times]
Begin time=001:0000
End time=001:0060
Timestep=120.0

[Meteo]
Include Rainfall=1
Rainfall file=rain_fixed.txt
Rainfall Directory=/home/jovyan/work/LISEM/inputfiles/VNIIMZ_20m

[Infiltration]
Include Infiltration=0
Infil Method=0

[Flow]
Routing Kin Wave 2D=1
Flow Boundary 2D=0
Use 2D Diagonal flow=0

[Erosion]
Include Erosion simulation=0

[Calibration]
Grain Size calibration D50=1
Grain Size calibration D90=1
Smax calibration=1
RR calibration=1
Ksat calibration=1
Ksat2 calibration=1
Ksat3 calibration=1
N calibration=1
Theta calibration=1
Psi calibration=1
Channel Ksat calibration=1
Channel N calibration=1
Boundary water level calibration=0
Channel tortuosity=1
Cohesion calibration=1
Cohesion Channel calibration=1
Aggregate stability calibration=1
Culvert size calibration=1

[Advanced]
Nr user Cores=1
Flooding SWOF Reconstruction=0
Flooding SWOF flux limiter=0
Correct MB with WH=0
Flood max iterations=10
Use time avg V=0
Erosion outside 2D loop=0
Pit Value=0
Use linked list=0
Use Perimeter KW=0
Use Channel Kinwave dt=0
Channel KinWave dt=0
Use Channel Max V=0
Channel Max V=0
Channel 2D flow connect=0
SWATRE precision=0
Advanced Options=0

[map names]

[Catchment]
dem=dem.map
grad=grad.map
ldd=ldd.map
outlet=outlet.map

[Landuse]
landunit=landunit.map
cover=per.map

[Surface]
rr=rr.map
manning=n.map